// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transactions.Business.Data;

namespace Transactions.Business.Migrations
{
    [DbContext(typeof(TransactionsContext))]
    [Migration("20200318102407_TransactionHistory_Added")]
    partial class TransactionHistory_Added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transactions.Business.Entities.CreditCardTokenDetails", b =>
                {
                    b.Property<long>("CreditCardTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CardBin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardExpiration")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<string>("CardOwnerNationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<long>("MerchantID")
                        .HasColumnType("bigint");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64)
                        .IsUnicode(false);

                    b.Property<long>("TerminalID")
                        .HasColumnType("bigint");

                    b.HasKey("CreditCardTokenID");

                    b.ToTable("CreditCardTokenDetails");
                });

            modelBuilder.Entity("Transactions.Business.Entities.PaymentTransaction", b =>
                {
                    b.Property<long>("PaymentTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AggregatorID")
                        .HasColumnType("bigint");

                    b.Property<string>("AggregatorTerminalID")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<long?>("BillingOrderID")
                        .HasColumnType("bigint");

                    b.Property<int>("CardPresence")
                        .HasColumnType("int");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("CurrentInstallment")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialPaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InitialTransactionID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InstallmentPaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InvoicingID")
                        .HasColumnType("bigint");

                    b.Property<long?>("MarketerID")
                        .HasColumnType("bigint");

                    b.Property<long>("MerchantID")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberOfPayments")
                        .HasColumnType("int");

                    b.Property<long?>("ProcessorID")
                        .HasColumnType("bigint");

                    b.Property<string>("ProcessorTerminalID")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("RejectionReason")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("TerminalID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TransactionNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TransactionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<byte[]>("UpdateTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentTransactionID");

                    b.ToTable("PaymentTransaction");
                });

            modelBuilder.Entity("Transactions.Business.Entities.TransactionHistory", b =>
                {
                    b.Property<long>("TransactionHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("IntegrationMessageId")
                        .HasColumnName("IntegrationMessageId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<DateTime?>("OperationDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationDescription")
                        .HasColumnType("nvarchar(max)")
                        .IsUnicode(true);

                    b.Property<string>("OperationDoneBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("OperationDoneByID")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("OperationMessage")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(true);

                    b.Property<long?>("PaymentTransactionID")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("TransactionHistoryID");

                    b.ToTable("TransactionHistory");
                });

            modelBuilder.Entity("Transactions.Business.Entities.PaymentTransaction", b =>
                {
                    b.OwnsOne("Transactions.Business.Entities.ClearingHouseTransactionDetails", "ClearingHouseTransactionDetails", b1 =>
                        {
                            b1.Property<long>("PaymentTransactionID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<long?>("ClearingHouseTransactionID")
                                .HasColumnName("ClearingHouseTransactionID")
                                .HasColumnType("bigint");

                            b1.HasKey("PaymentTransactionID");

                            b1.ToTable("PaymentTransaction");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionID");
                        });

                    b.OwnsOne("Transactions.Business.Entities.CreditCardDetails", "CreditCardDetails", b1 =>
                        {
                            b1.Property<long>("PaymentTransactionID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CardBin")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CardExpiration")
                                .HasColumnName("CardExpiration")
                                .HasColumnType("varchar(5)")
                                .HasMaxLength(5)
                                .IsUnicode(false);

                            b1.Property<string>("CardNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CardOwnerName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CardOwnerNationalID")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CardToken")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CardVendor")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsTourist")
                                .HasColumnType("bit");

                            b1.HasKey("PaymentTransactionID");

                            b1.ToTable("PaymentTransaction");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionID");
                        });

                    b.OwnsOne("Transactions.Business.Entities.DealDetails", "DealDetails", b1 =>
                        {
                            b1.Property<long>("PaymentTransactionID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("ConsumerEmail")
                                .HasColumnName("ConsumerEmail")
                                .HasColumnType("varchar(50)")
                                .HasMaxLength(50)
                                .IsUnicode(false);

                            b1.Property<string>("ConsumerIP")
                                .HasColumnName("ConsumerIP")
                                .HasColumnType("varchar(32)")
                                .HasMaxLength(32)
                                .IsUnicode(false);

                            b1.Property<string>("ConsumerPhone")
                                .HasColumnName("ConsumerPhone")
                                .HasColumnType("varchar(20)")
                                .HasMaxLength(20)
                                .IsUnicode(false);

                            b1.Property<string>("DealDescription")
                                .HasColumnName("DealDescription")
                                .HasColumnType("nvarchar(max)")
                                .IsUnicode(true);

                            b1.Property<string>("MerchantIP")
                                .HasColumnName("MerchantIP")
                                .HasColumnType("varchar(32)")
                                .HasMaxLength(32)
                                .IsUnicode(false);

                            b1.HasKey("PaymentTransactionID");

                            b1.ToTable("PaymentTransaction");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionID");
                        });

                    b.OwnsOne("Transactions.Business.Entities.ShvaTransactionDetails", "ShvaTransactionDetails", b1 =>
                        {
                            b1.Property<long>("PaymentTransactionID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("ManuallyTransmitted")
                                .HasColumnName("ManuallyTransmitted")
                                .HasColumnType("bit");

                            b1.Property<string>("ShvaDealID")
                                .HasColumnName("ShvaDealID")
                                .HasColumnType("varchar(20)")
                                .HasMaxLength(20)
                                .IsUnicode(false);

                            b1.Property<string>("ShvaShovarNumber")
                                .HasColumnName("ShvaShovarNumber")
                                .HasColumnType("varchar(20)")
                                .HasMaxLength(20)
                                .IsUnicode(false);

                            b1.Property<string>("ShvaTerminalID")
                                .HasColumnName("ShvaTerminalID")
                                .HasColumnType("varchar(20)")
                                .HasMaxLength(20)
                                .IsUnicode(false);

                            b1.Property<string>("ShvaTransmissionNumber")
                                .HasColumnName("ShvaTransmissionNumber")
                                .HasColumnType("varchar(20)")
                                .HasMaxLength(20)
                                .IsUnicode(false);

                            b1.Property<DateTime?>("TransmissionDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("PaymentTransactionID");

                            b1.ToTable("PaymentTransaction");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionID");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
