//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckoutPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckoutPortal.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Code.
        /// </summary>
        public static string AuthorizationCode {
            get {
                return ResourceManager.GetString("AuthorizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Code (optional).
        /// </summary>
        public static string AuthorizationCodeOptional {
            get {
                return ResourceManager.GetString("AuthorizationCodeOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Payment.
        /// </summary>
        public static string BitPayment {
            get {
                return ResourceManager.GetString("BitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel payment.
        /// </summary>
        public static string CancelPayment {
            get {
                return ResourceManager.GetString("CancelPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name On Card.
        /// </summary>
        public static string CardOwnerName {
            get {
                return ResourceManager.GetString("CardOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose payment method.
        /// </summary>
        public static string ChoosePaymentMethod {
            get {
                return ResourceManager.GetString("ChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Payment.
        /// </summary>
        public static string CreditCardPayment {
            get {
                return ResourceManager.GetString("CreditCardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyCard is Israel&apos;s leading payment gateway for SMB merchants..
        /// </summary>
        public static string EcwidGeneralInfoMessage {
            get {
                return ResourceManager.GetString("EcwidGeneralInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use EasyCard you only need to specify Terminal API key.
        /// </summary>
        public static string EcwidSettingsInfoMessage {
            get {
                return ResourceManager.GetString("EcwidSettingsInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new Card.
        /// </summary>
        public static string EnterNewCard {
            get {
                return ResourceManager.GetString("EnterNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to Payment.
        /// </summary>
        public static string GoBackToPayment {
            get {
                return ResourceManager.GetString("GoBackToPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to set up.
        /// </summary>
        public static string HowToSetUp {
            get {
                return ResourceManager.GetString("HowToSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate.
        /// </summary>
        public static string Immediate {
            get {
                return ResourceManager.GetString("Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial payment.
        /// </summary>
        public static string InitialPayment {
            get {
                return ResourceManager.GetString("InitialPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of first payment.
        /// </summary>
        public static string InitialPaymentAmount {
            get {
                return ResourceManager.GetString("InitialPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment.
        /// </summary>
        public static string Installments {
            get {
                return ResourceManager.GetString("Installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Pinpad Deal.
        /// </summary>
        public static string MakePinPadDeal {
            get {
                return ResourceManager.GetString("MakePinPadDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID must be valid Israeli National ID.
        /// </summary>
        public static string NationalIDInvalid {
            get {
                return ResourceManager.GetString("NationalIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of payments.
        /// </summary>
        public static string NumberOfPayments {
            get {
                return ResourceManager.GetString("NumberOfPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of payments must be less than @max.
        /// </summary>
        public static string NumberOfPaymentsMustBeLessThan {
            get {
                return ResourceManager.GetString("NumberOfPaymentsMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add card.
        /// </summary>
        public static string OnlyAddCard {
            get {
                return ResourceManager.GetString("OnlyAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer&apos;s name.
        /// </summary>
        public static string PayersName {
            get {
                return ResourceManager.GetString("PayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment amount.
        /// </summary>
        public static string PaymentAmount {
            get {
                return ResourceManager.GetString("PaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment canceled.
        /// </summary>
        public static string PaymentCanceled {
            get {
                return ResourceManager.GetString("PaymentCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Error.
        /// </summary>
        public static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment link no longer available.
        /// </summary>
        public static string PaymentLinkNoLongerAvailable {
            get {
                return ResourceManager.GetString("PaymentLinkNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successful.
        /// </summary>
        public static string PaymentSuccessful {
            get {
                return ResourceManager.GetString("PaymentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with Android.
        /// </summary>
        public static string PayWithAndroid {
            get {
                return ResourceManager.GetString("PayWithAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with Bit.
        /// </summary>
        public static string PayWithBit {
            get {
                return ResourceManager.GetString("PayWithBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with EasyCard.
        /// </summary>
        public static string PayWithEasyCard {
            get {
                return ResourceManager.GetString("PayWithEasyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with IOS.
        /// </summary>
        public static string PayWithIOS {
            get {
                return ResourceManager.GetString("PayWithIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Deal.
        /// </summary>
        public static string RegularDeal {
            get {
                return ResourceManager.GetString("RegularDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Payment.
        /// </summary>
        public static string RegularPayment {
            get {
                return ResourceManager.GetString("RegularPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID.
        /// </summary>
        public static string RequestID {
            get {
                return ResourceManager.GetString("RequestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Card.
        /// </summary>
        public static string SaveCard {
            get {
                return ResourceManager.GetString("SaveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were saved successfully.
        /// </summary>
        public static string SettingsWereSavedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsWereSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Api Key.
        /// </summary>
        public static string TerminalApiKey {
            get {
                return ResourceManager.GetString("TerminalApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This credit card is already added as Token.
        /// </summary>
        public static string ThisCreditCardIsAlreadyAddedAsToken {
            get {
                return ResourceManager.GetString("ThisCreditCardIsAlreadyAddedAsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Secure Error.
        /// </summary>
        public static string ThreeDSError {
            get {
                return ResourceManager.GetString("ThreeDSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sum.
        /// </summary>
        public static string TotalSum {
            get {
                return ResourceManager.GetString("TotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use saved card.
        /// </summary>
        public static string UseSavedCard {
            get {
                return ResourceManager.GetString("UseSavedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make a payment please use link provided by merchant..
        /// </summary>
        public static string WelcomeTextBottom {
            get {
                return ResourceManager.GetString("WelcomeTextBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the checkout portal.
        /// </summary>
        public static string WelcomeTextTop {
            get {
                return ResourceManager.GetString("WelcomeTextTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now close the page.
        /// </summary>
        public static string YouCanNowCloseThePage {
            get {
                return ResourceManager.GetString("YouCanNowCloseThePage", resourceCulture);
            }
        }
    }
}
