# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'


- script: npm install
  displayName: 'npm install'
  workingDirectory: 'EasyCard\UI\merchant'
  
- script: npm run build
  displayName: 'npm build'
  workingDirectory: 'EasyCard\UI\merchant'

- script: npm install
  displayName: 'npm install'
  workingDirectory: 'EasyCard\UI\admin'

- script: npm run build
  displayName: 'npm build'
  workingDirectory: 'EasyCard\UI\admin'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/EasyCard/UI/merchant/dist'
    Contents: '**'
    TargetFolder: '$(system.defaultworkingdirectory)/EasyCard/MerchantProfileApi/wwwroot'
    overWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)/EasyCard/UI/admin/dist'
    Contents: '**'
    TargetFolder: '$(system.defaultworkingdirectory)/EasyCard/Merchants.Api/wwwroot'
    overWrite: true

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '
    /p:DeployOnBuild=true
    /p:WebPublishMethod=Package
    /p:PackageAsSingleFile=false
    /p:SkipInvalidConfigurations=true
    /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'



- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: |
      Transactions.Api.zip
      MerchantProfileApi.zip
      Merchants.Api.zip
      IdentityServer.zip
      CheckoutPortal.zip
    TargetFolder: '$(Build.ArtifactStagingDirectory)/publishable'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publishable'
    ArtifactName: 'publishable'
    publishLocation: 'Container'




