//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Integration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RejectionReasonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RejectionReasonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Integration.Resources.RejectionReasonResource", typeof(RejectionReasonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner national id required.
        /// </summary>
        public static string CardOwnerNationalIdRequired {
            get {
                return ResourceManager.GetString("CardOwnerNationalIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card daily usage exceeded.
        /// </summary>
        public static string CreditCardDailyUsageExceeded {
            get {
                return ResourceManager.GetString("CreditCardDailyUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card is merchants card.
        /// </summary>
        public static string CreditCardIsMerchantsCard {
            get {
                return ResourceManager.GetString("CreditCardIsMerchantsCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily amount exceeded.
        /// </summary>
        public static string DailyAmountExceeded {
            get {
                return ResourceManager.GetString("DailyAmountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National id is merchants id.
        /// </summary>
        public static string NationalIdIsMerchantsId {
            get {
                return ResourceManager.GetString("NationalIdIsMerchantsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund exceeded collateral.
        /// </summary>
        public static string RefundExceededCollateral {
            get {
                return ResourceManager.GetString("RefundExceededCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund not match regular amount.
        /// </summary>
        public static string RefundNotMatchRegularAmount {
            get {
                return ResourceManager.GetString("RefundNotMatchRegularAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single transaction amount exceeded.
        /// </summary>
        public static string SingleTransactionAmountExceeded {
            get {
                return ResourceManager.GetString("SingleTransactionAmountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
