//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactions.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transactions.Shared.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregator is not defined.
        /// </summary>
        public static string AggregatorNotDefined {
            get {
                return ResourceManager.GetString("AggregatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner national ID required.
        /// </summary>
        public static string CardOwnerNationalIDRequired {
            get {
                return ResourceManager.GetString("CardOwnerNationalIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner national ID required, but it is not present in stored credit card token.
        /// </summary>
        public static string CardOwnerNationalIDRequiredButNotPresentInToken {
            get {
                return ResourceManager.GetString("CardOwnerNationalIDRequiredButNotPresentInToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create transaction request sent to {0}.
        /// </summary>
        public static string CreateRequestSentToAggregator {
            get {
                return ResourceManager.GetString("CreateRequestSentToAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCardSecureDetails required.
        /// </summary>
        public static string CreditCardSecureDetailsRequired {
            get {
                return ResourceManager.GetString("CreditCardSecureDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCardSecureDetails should be omitted in case if credit card token present.
        /// </summary>
        public static string CreditCardSecureDetailsShouldBeOmitted {
            get {
                return ResourceManager.GetString("CreditCardSecureDetailsShouldBeOmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV required.
        /// </summary>
        public static string CvvRequired {
            get {
                return ResourceManager.GetString("CvvRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV required, but stored credit card token cannot use cvv.
        /// </summary>
        public static string CvvRequiredButStoredTokenCannotUseCvv {
            get {
                return ResourceManager.GetString("CvvRequiredButStoredTokenCannotUseCvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Process Transaction.
        /// </summary>
        public static string FailedToProcessTransaction {
            get {
                return ResourceManager.GetString("FailedToProcessTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallmentDetails required.
        /// </summary>
        public static string InstallmentDetailsRequired {
            get {
                return ResourceManager.GetString("InstallmentDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfPayments should be greater than or equal {0}.
        /// </summary>
        public static string NumberOfPaymentsShouldBeGreaterThan {
            get {
                return ResourceManager.GetString("NumberOfPaymentsShouldBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfPayments should be less than or equal {0}.
        /// </summary>
        public static string NumberOfPaymentsShouldBeLessThan {
            get {
                return ResourceManager.GetString("NumberOfPaymentsShouldBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check specified values.
        /// </summary>
        public static string PleaseCheckValues {
            get {
                return ResourceManager.GetString("PleaseCheckValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor is not defined.
        /// </summary>
        public static string ProcessorNotDefined {
            get {
                return ResourceManager.GetString("ProcessorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction rejected by Aggregator.
        /// </summary>
        public static string RejectedByAggregator {
            get {
                return ResourceManager.GetString("RejectedByAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction rejected by Processor.
        /// </summary>
        public static string RejectedByProcessor {
            get {
                return ResourceManager.GetString("RejectedByProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Token Created.
        /// </summary>
        public static string TokenCreated {
            get {
                return ResourceManager.GetString("TokenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Token Deleted.
        /// </summary>
        public static string TokenDeleted {
            get {
                return ResourceManager.GetString("TokenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalAmount of installment payments is invalid.
        /// </summary>
        public static string TotalAmountIsInvalid {
            get {
                return ResourceManager.GetString("TotalAmountIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Created.
        /// </summary>
        public static string TransactionCreated {
            get {
                return ResourceManager.GetString("TransactionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Transmission Failed.
        /// </summary>
        public static string TransactionsTransmissionFailed {
            get {
                return ResourceManager.GetString("TransactionsTransmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Transmitted.
        /// </summary>
        public static string TransactionsTransmitted {
            get {
                return ResourceManager.GetString("TransactionsTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Updated.
        /// </summary>
        public static string TransactionUpdated {
            get {
                return ResourceManager.GetString("TransactionUpdated", resourceCulture);
            }
        }
    }
}
