//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactions.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transactions.Shared.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregator is not defined.
        /// </summary>
        public static string AggregatorNotDefined {
            get {
                return ResourceManager.GetString("AggregatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount required for pinpad deal.
        /// </summary>
        public static string AmountRequiredForPinpadDeal {
            get {
                return ResourceManager.GetString("AmountRequiredForPinpadDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve transaction on device.
        /// </summary>
        public static string ApproveTransactionOnDevice {
            get {
                return ResourceManager.GetString("ApproveTransactionOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization code is required. Call @number and tell them the supplier number @retailer to get the authorization code and create a new transaction with it specified..
        /// </summary>
        public static string AuthorizationCodeRequired {
            get {
                return ResourceManager.GetString("AuthorizationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting for Transmission.
        /// </summary>
        public static string AwaitingForTransmission {
            get {
                return ResourceManager.GetString("AwaitingForTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Deal Created.
        /// </summary>
        public static string BillingDealCreated {
            get {
                return ResourceManager.GetString("BillingDealCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Deal Deactivated.
        /// </summary>
        public static string BillingDealDeactivated {
            get {
                return ResourceManager.GetString("BillingDealDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Deal Deleted.
        /// </summary>
        public static string BillingDealDeleted {
            get {
                return ResourceManager.GetString("BillingDealDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing deal is closed.
        /// </summary>
        public static string BillingDealIsClosed {
            get {
                return ResourceManager.GetString("BillingDealIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Deal Paused.
        /// </summary>
        public static string BillingDealPaused {
            get {
                return ResourceManager.GetString("BillingDealPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of billing deals for transaction batch is limited to {0}.
        /// </summary>
        public static string BillingDealsMaxBatchSize {
            get {
                return ResourceManager.GetString("BillingDealsMaxBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Deals required.
        /// </summary>
        public static string BillingDealsRequired {
            get {
                return ResourceManager.GetString("BillingDealsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Deal Unpaused.
        /// </summary>
        public static string BillingDealUnpaused {
            get {
                return ResourceManager.GetString("BillingDealUnpaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Deal Updated.
        /// </summary>
        public static string BillingDealUpdated {
            get {
                return ResourceManager.GetString("BillingDealUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled By Aggregator.
        /// </summary>
        public static string CanceledByAggregator {
            get {
                return ResourceManager.GetString("CanceledByAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled By Merchant.
        /// </summary>
        public static string CancelledByMerchant {
            get {
                return ResourceManager.GetString("CancelledByMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel invoiced transaction.
        /// </summary>
        public static string CannotCancelInvoicedTransaction {
            get {
                return ResourceManager.GetString("CannotCancelInvoicedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only issue invoice for ILS transactions.
        /// </summary>
        public static string CanOnlyIssueInvoiceForILSTransactions {
            get {
                return ResourceManager.GetString("CanOnlyIssueInvoiceForILSTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID must be valid Israeli National ID.
        /// </summary>
        public static string CardOwnerNationalIDInvalid {
            get {
                return ResourceManager.GetString("CardOwnerNationalIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner national ID required.
        /// </summary>
        public static string CardOwnerNationalIDRequired {
            get {
                return ResourceManager.GetString("CardOwnerNationalIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner national ID required, but it is not present in stored credit card token.
        /// </summary>
        public static string CardOwnerNationalIDRequiredButNotPresentInToken {
            get {
                return ResourceManager.GetString("CardOwnerNationalIDRequiredButNotPresentInToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Reader Input Required.
        /// </summary>
        public static string CardReaderInputRequired {
            get {
                return ResourceManager.GetString("CardReaderInputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Feature must be enabled.
        /// </summary>
        public static string CheckoutFeatureMustBeEnabled {
            get {
                return ResourceManager.GetString("CheckoutFeatureMustBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commited By Aggregator.
        /// </summary>
        public static string CommitedByAggregator {
            get {
                return ResourceManager.GetString("CommitedByAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed By Aggregator.
        /// </summary>
        public static string ConfirmedByAggregator {
            get {
                return ResourceManager.GetString("ConfirmedByAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed By Processor.
        /// </summary>
        public static string ConfirmedByProcessor {
            get {
                return ResourceManager.GetString("ConfirmedByProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Name and Consumer Email are required.
        /// </summary>
        public static string ConsumerNameAndConsumerEmailRequired {
            get {
                return ResourceManager.GetString("ConsumerNameAndConsumerEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer National Id is not equal to credit card National Id.
        /// </summary>
        public static string ConsumerNatIdIsNotEqTranNatId {
            get {
                return ResourceManager.GetString("ConsumerNatIdIsNotEqTranNatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create transaction request sent to {0}.
        /// </summary>
        public static string CreateRequestSentToAggregator {
            get {
                return ResourceManager.GetString("CreateRequestSentToAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card expired.
        /// </summary>
        public static string CreditCardExpired {
            get {
                return ResourceManager.GetString("CreditCardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCardSecureDetails required.
        /// </summary>
        public static string CreditCardSecureDetailsRequired {
            get {
                return ResourceManager.GetString("CreditCardSecureDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCardSecureDetails should be omitted in case if credit card token present.
        /// </summary>
        public static string CreditCardSecureDetailsShouldBeOmitted {
            get {
                return ResourceManager.GetString("CreditCardSecureDetailsShouldBeOmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Token changed.
        /// </summary>
        public static string CreditCardTokenChanged {
            get {
                return ResourceManager.GetString("CreditCardTokenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV required.
        /// </summary>
        public static string CvvRequired {
            get {
                return ResourceManager.GetString("CvvRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV required, but stored credit card token cannot use cvv.
        /// </summary>
        public static string CvvRequiredButStoredTokenCannotUseCvv {
            get {
                return ResourceManager.GetString("CvvRequiredButStoredTokenCannotUseCvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is processing transaction.
        /// </summary>
        public static string DeviceIsProcessingTransaction {
            get {
                return ResourceManager.GetString("DeviceIsProcessingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAddressRequired.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Cancel By Aggregator.
        /// </summary>
        public static string FailedToCancelByAggregator {
            get {
                return ResourceManager.GetString("FailedToCancelByAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Commit By Aggregator.
        /// </summary>
        public static string FailedToCommitByAggregator {
            get {
                return ResourceManager.GetString("FailedToCommitByAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Confirm By Aggregator.
        /// </summary>
        public static string FailedToConfirmByAggregator {
            get {
                return ResourceManager.GetString("FailedToConfirmByAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Confirm By Procesor.
        /// </summary>
        public static string FailedToConfirmByProcesor {
            get {
                return ResourceManager.GetString("FailedToConfirmByProcesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Credit Card Token.
        /// </summary>
        public static string FailedToCreateCCToken {
            get {
                return ResourceManager.GetString("FailedToCreateCCToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Invoice.
        /// </summary>
        public static string FailedToCreateInvoice {
            get {
                return ResourceManager.GetString("FailedToCreateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Process Transaction.
        /// </summary>
        public static string FailedToProcessTransaction {
            get {
                return ResourceManager.GetString("FailedToProcessTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallmentDetails required.
        /// </summary>
        public static string InstallmentDetailsRequired {
            get {
                return ResourceManager.GetString("InstallmentDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Created.
        /// </summary>
        public static string InvoiceCreated {
            get {
                return ResourceManager.GetString("InvoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice generated.
        /// </summary>
        public static string InvoiceGenerated {
            get {
                return ResourceManager.GetString("InvoiceGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice generation failed.
        /// </summary>
        public static string InvoiceGenerationFailed {
            get {
                return ResourceManager.GetString("InvoiceGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices are required.
        /// </summary>
        public static string InvoicesForResendRequired {
            get {
                return ResourceManager.GetString("InvoicesForResendRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices queued for resend.
        /// </summary>
        public static string InvoicesQueuedForResend {
            get {
                return ResourceManager.GetString("InvoicesQueuedForResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice State is not valid.
        /// </summary>
        public static string InvoiceStateIsNotValid {
            get {
                return ResourceManager.GetString("InvoiceStateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicing system is not defined.
        /// </summary>
        public static string InvoicingNotDefined {
            get {
                return ResourceManager.GetString("InvoicingNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J2 deal is not allowed.
        /// </summary>
        public static string J2NotAllowed {
            get {
                return ResourceManager.GetString("J2NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J5 Expiration date is {0}.
        /// </summary>
        public static string J5ExpirationDate {
            get {
                return ResourceManager.GetString("J5ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J5 transaction was expired.
        /// </summary>
        public static string J5Expired {
            get {
                return ResourceManager.GetString("J5Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J5 deal is not allowed.
        /// </summary>
        public static string J5NotAllowed {
            get {
                return ResourceManager.GetString("J5NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masav File generated successfully.
        /// </summary>
        public static string MasavFileGeneratedSuccessfully {
            get {
                return ResourceManager.GetString("MasavFileGeneratedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masav File was not generated.
        /// </summary>
        public static string MasavFileWasNotGenerated {
            get {
                return ResourceManager.GetString("MasavFileWasNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to transmit.
        /// </summary>
        public static string NothingToTransmit {
            get {
                return ResourceManager.GetString("NothingToTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfPayments should be greater than or equal {0}.
        /// </summary>
        public static string NumberOfPaymentsShouldBeGreaterThan {
            get {
                return ResourceManager.GetString("NumberOfPaymentsShouldBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfPayments should be less than or equal {0}.
        /// </summary>
        public static string NumberOfPaymentsShouldBeLessThan {
            get {
                return ResourceManager.GetString("NumberOfPaymentsShouldBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only successful transactions are allowed.
        /// </summary>
        public static string OnlySuccessfulTransactionsAreAllowed {
            get {
                return ResourceManager.GetString("OnlySuccessfulTransactionsAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Request canceled.
        /// </summary>
        public static string PaymentRequestCanceled {
            get {
                return ResourceManager.GetString("PaymentRequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Request created.
        /// </summary>
        public static string PaymentRequestCreated {
            get {
                return ResourceManager.GetString("PaymentRequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment request payment failed.
        /// </summary>
        public static string PaymentRequestPaymentFailed {
            get {
                return ResourceManager.GetString("PaymentRequestPaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Request payed.
        /// </summary>
        public static string PaymentRequestPaymentSuccessed {
            get {
                return ResourceManager.GetString("PaymentRequestPaymentSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Request Is Closed.
        /// </summary>
        public static string PaymentRequestStatusIsClosed {
            get {
                return ResourceManager.GetString("PaymentRequestStatusIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Request Updated.
        /// </summary>
        public static string PaymentRequestUpdated {
            get {
                return ResourceManager.GetString("PaymentRequestUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type can not be changed.
        /// </summary>
        public static string PaymentTypeCannotBeChanged {
            get {
                return ResourceManager.GetString("PaymentTypeCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check specified values.
        /// </summary>
        public static string PleaseCheckValues {
            get {
                return ResourceManager.GetString("PleaseCheckValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of entities for processing batch is limited to {0}.
        /// </summary>
        public static string ProcesingItemsLimit {
            get {
                return ResourceManager.GetString("ProcesingItemsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor is not defined.
        /// </summary>
        public static string ProcessorNotDefined {
            get {
                return ResourceManager.GetString("ProcessorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction rejected by Aggregator.
        /// </summary>
        public static string RejectedByAggregator {
            get {
                return ResourceManager.GetString("RejectedByAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction rejected by Processor.
        /// </summary>
        public static string RejectedByProcessor {
            get {
                return ResourceManager.GetString("RejectedByProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal for update parameters is required.
        /// </summary>
        public static string TerminalForUpdateParametersRequired {
            get {
                return ResourceManager.GetString("TerminalForUpdateParametersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal must have Bank details specified.
        /// </summary>
        public static string TerminalMustHaveBankDetailsSpecified {
            get {
                return ResourceManager.GetString("TerminalMustHaveBankDetailsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no invoices to resend.
        /// </summary>
        public static string ThereAreNoInvoicesToResend {
            get {
                return ResourceManager.GetString("ThereAreNoInvoicesToResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no transactions to transmit.
        /// </summary>
        public static string ThereAreNoTransactionsToTransmit {
            get {
                return ResourceManager.GetString("ThereAreNoTransactionsToTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Token Created.
        /// </summary>
        public static string TokenCreated {
            get {
                return ResourceManager.GetString("TokenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Token Deleted.
        /// </summary>
        public static string TokenDeleted {
            get {
                return ResourceManager.GetString("TokenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalAmount of installment payments is invalid.
        /// </summary>
        public static string TotalAmountIsInvalid {
            get {
                return ResourceManager.GetString("TotalAmountIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction already has invoice.
        /// </summary>
        public static string TransactionAlreadyHasInvoice {
            get {
                return ResourceManager.GetString("TransactionAlreadyHasInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Canceled.
        /// </summary>
        public static string TransactionCanceled {
            get {
                return ResourceManager.GetString("TransactionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Created.
        /// </summary>
        public static string TransactionCreated {
            get {
                return ResourceManager.GetString("TransactionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction must be completed.
        /// </summary>
        public static string TransactionMustBeCompleted {
            get {
                return ResourceManager.GetString("TransactionMustBeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions list for transmission is required.
        /// </summary>
        public static string TransactionsForTransmissionRequired {
            get {
                return ResourceManager.GetString("TransactionsForTransmissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions queued.
        /// </summary>
        public static string TransactionsQueued {
            get {
                return ResourceManager.GetString("TransactionsQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Status is not valid for this operation.
        /// </summary>
        public static string TransactionStatusIsNotValid {
            get {
                return ResourceManager.GetString("TransactionStatusIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Transmission Failed.
        /// </summary>
        public static string TransactionsTransmissionFailed {
            get {
                return ResourceManager.GetString("TransactionsTransmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Transmitted.
        /// </summary>
        public static string TransactionsTransmitted {
            get {
                return ResourceManager.GetString("TransactionsTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Updated.
        /// </summary>
        public static string TransactionUpdated {
            get {
                return ResourceManager.GetString("TransactionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission Canceling In Progress.
        /// </summary>
        public static string TransmissionCancelingInProgress {
            get {
                return ResourceManager.GetString("TransmissionCancelingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission In Progress.
        /// </summary>
        public static string TransmissionInProgress {
            get {
                return ResourceManager.GetString("TransmissionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of transactions for transmission batch is limited to {0}.
        /// </summary>
        public static string TransmissionLimit {
            get {
                return ResourceManager.GetString("TransmissionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission To Processor Failed.
        /// </summary>
        public static string TransmissionToProcessorFailed {
            get {
                return ResourceManager.GetString("TransmissionToProcessorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmitted By Processor.
        /// </summary>
        public static string TransmittedByProcessor {
            get {
                return ResourceManager.GetString("TransmittedByProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Request Viewed.
        /// </summary>
        public static string Viewed {
            get {
                return ResourceManager.GetString("Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When saved credit card token specified, credit card details should be omitted.
        /// </summary>
        public static string WhenSpecifiedTokenCCDetailsShouldBeOmitted {
            get {
                return ResourceManager.GetString("WhenSpecifiedTokenCCDetailsShouldBeOmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When saved credit card token specified, &quot;Save Credit Card&quot; flag is not valid.
        /// </summary>
        public static string WhenSpecifiedTokenCCDIsNotValid {
            get {
                return ResourceManager.GetString("WhenSpecifiedTokenCCDIsNotValid", resourceCulture);
            }
        }
    }
}
