//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactions.Shared.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transactions.Shared.Messages.ApiMessages", typeof(ApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account is required for KYC approval.
        /// </summary>
        public static string BankAccountRequiredForKYC {
            get {
                return ResourceManager.GetString("BankAccountRequiredForKYC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing report already payed.
        /// </summary>
        public static string BillingReportAlreadyPayed {
            get {
                return ResourceManager.GetString("BillingReportAlreadyPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing report updated.
        /// </summary>
        public static string BillingReportUpdated {
            get {
                return ResourceManager.GetString("BillingReportUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday date is invalid.
        /// </summary>
        public static string BirthdayInvalid {
            get {
                return ResourceManager.GetString("BirthdayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s account cannot be locked.
        /// </summary>
        public static string CannotLockAccount {
            get {
                return ResourceManager.GetString("CannotLockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s account password cannot be reseted.
        /// </summary>
        public static string CannotResetPassowrd {
            get {
                return ResourceManager.GetString("CannotResetPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send invitation.
        /// </summary>
        public static string CannotSendInvitation {
            get {
                return ResourceManager.GetString("CannotSendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s account cannot be unlocked.
        /// </summary>
        public static string CannotUnlockAccount {
            get {
                return ResourceManager.GetString("CannotUnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargeback amount is invalid.
        /// </summary>
        public static string ChargebackAmountIsInvalid {
            get {
                return ResourceManager.GetString("ChargebackAmountIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargeback request created.
        /// </summary>
        public static string ChargebackCreated {
            get {
                return ResourceManager.GetString("ChargebackCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargeback request done.
        /// </summary>
        public static string ChargebackDone {
            get {
                return ResourceManager.GetString("ChargebackDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargeback request failed.
        /// </summary>
        public static string ChargebackFailed {
            get {
                return ResourceManager.GetString("ChargebackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Limit changed.
        /// </summary>
        public static string CollateralLimitChanged {
            get {
                return ResourceManager.GetString("CollateralLimitChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comission rates changed.
        /// </summary>
        public static string ComissionRatesChanged {
            get {
                return ResourceManager.GetString("ComissionRatesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change comission rates.
        /// </summary>
        public static string ComissionRatesFailed {
            get {
                return ResourceManager.GetString("ComissionRatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card cannot be charged.
        /// </summary>
        public static string CreditCardCannotBeCharged {
            get {
                return ResourceManager.GetString("CreditCardCannotBeCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card token obtaining failed.
        /// </summary>
        public static string CreditCardTokenFailed {
            get {
                return ResourceManager.GetString("CreditCardTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Token Obtained.
        /// </summary>
        public static string CreditCardTokenObtained {
            get {
                return ResourceManager.GetString("CreditCardTokenObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document deleted.
        /// </summary>
        public static string DocumentDeleted {
            get {
                return ResourceManager.GetString("DocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document does not exist.
        /// </summary>
        public static string DocumentDoesNotExist {
            get {
                return ResourceManager.GetString("DocumentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document updated.
        /// </summary>
        public static string DocumentUpdated {
            get {
                return ResourceManager.GetString("DocumentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document uploaded.
        /// </summary>
        public static string DocumentUploaded {
            get {
                return ResourceManager.GetString("DocumentUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email changing disabled.
        /// </summary>
        public static string EmailChangingIsDisabled {
            get {
                return ResourceManager.GetString("EmailChangingIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity detailds updated.
        /// </summary>
        public static string IdentityDetaildsUpdated {
            get {
                return ResourceManager.GetString("IdentityDetaildsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Transaction Does Not Exist.
        /// </summary>
        public static string InitialTransactionDoesNotExist {
            get {
                return ResourceManager.GetString("InitialTransactionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payment Gateway ID provided.
        /// </summary>
        public static string InvalidPaymentGatewayID {
            get {
                return ResourceManager.GetString("InvalidPaymentGatewayID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation sent to {email}.
        /// </summary>
        public static string InvitationSentTo {
            get {
                return ResourceManager.GetString("InvitationSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J5 block failed.
        /// </summary>
        public static string J5BlockFailed {
            get {
                return ResourceManager.GetString("J5BlockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s KYC information has been approved.
        /// </summary>
        public static string KYCApproved {
            get {
                return ResourceManager.GetString("KYCApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s KYC information has been rejected.
        /// </summary>
        public static string KYCRejected {
            get {
                return ResourceManager.GetString("KYCRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s KYC Status reseted because one of required documents is not present or not approved.
        /// </summary>
        public static string KYCStatusReseted {
            get {
                return ResourceManager.GetString("KYCStatusReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits updated.
        /// </summary>
        public static string LimitsUpdated {
            get {
                return ResourceManager.GetString("LimitsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Transaction Already Created.
        /// </summary>
        public static string ManualTransactionAlreadyCreated {
            get {
                return ResourceManager.GetString("ManualTransactionAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s account locked.
        /// </summary>
        public static string MerchantAccountLocked {
            get {
                return ResourceManager.GetString("MerchantAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s account unlocked.
        /// </summary>
        public static string MerchantAccountUnLocked {
            get {
                return ResourceManager.GetString("MerchantAccountUnLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant created.
        /// </summary>
        public static string MerchantCreated {
            get {
                return ResourceManager.GetString("MerchantCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared values changed.
        /// </summary>
        public static string MerchantDeclaredChanged {
            get {
                return ResourceManager.GetString("MerchantDeclaredChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant does not exist.
        /// </summary>
        public static string MerchantDoesNotExist {
            get {
                return ResourceManager.GetString("MerchantDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant with &quot;{0}&quot; already exists.
        /// </summary>
        public static string MerchantlNotUniqueueFields {
            get {
                return ResourceManager.GetString("MerchantlNotUniqueueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant fields &quot;{0}&quot; already in use.
        /// </summary>
        public static string MerchantlNotUniqueueHistoryFields {
            get {
                return ResourceManager.GetString("MerchantlNotUniqueueHistoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant updated.
        /// </summary>
        public static string MerchantUpdated {
            get {
                return ResourceManager.GetString("MerchantUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to register credit card first.
        /// </summary>
        public static string NeedToRegisterCreditCardFirst {
            get {
                return ResourceManager.GetString("NeedToRegisterCreditCardFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next KYC document types need to be approved.
        /// </summary>
        public static string NextKYCDocumentTypesNeedBeApproved {
            get {
                return ResourceManager.GetString("NextKYCDocumentTypesNeedBeApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikion Changed.
        /// </summary>
        public static string NikionChanged {
            get {
                return ResourceManager.GetString("NikionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nilion Rates Changed.
        /// </summary>
        public static string NikionRatesChanged {
            get {
                return ResourceManager.GetString("NikionRatesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transactions nikion rates recalculated.
        /// </summary>
        public static string NikionRatesRecalculation {
            get {
                return ResourceManager.GetString("NikionRatesRecalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transactions nikion rates recalculated to {1}.
        /// </summary>
        public static string NikionRatesRecalculationTo {
            get {
                return ResourceManager.GetString("NikionRatesRecalculationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant&apos;s account {email} password reseted.
        /// </summary>
        public static string PasswordReseted {
            get {
                return ResourceManager.GetString("PasswordReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates Added From System Settings.
        /// </summary>
        public static string RatesAddedFromSystemSettings {
            get {
                return ResourceManager.GetString("RatesAddedFromSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transactions rates recalculated.
        /// </summary>
        public static string RatesRecalculation {
            get {
                return ResourceManager.GetString("RatesRecalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transactions rates recalculated to {1}.
        /// </summary>
        public static string RatesRecalculationTo {
            get {
                return ResourceManager.GetString("RatesRecalculationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction rejection undone.
        /// </summary>
        public static string RejectionUndone {
            get {
                return ResourceManager.GetString("RejectionUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security J5 limit applied.
        /// </summary>
        public static string SecurityJ5BlockApplied {
            get {
                return ResourceManager.GetString("SecurityJ5BlockApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply security J5 limit.
        /// </summary>
        public static string SecurityJ5BlockFailed {
            get {
                return ResourceManager.GetString("SecurityJ5BlockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal record added. Please review rates and declared values..
        /// </summary>
        public static string TerminalAdded {
            get {
                return ResourceManager.GetString("TerminalAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal cannot be added to another terminal.
        /// </summary>
        public static string TerminalCanotBeAdedToTerminal {
            get {
                return ResourceManager.GetString("TerminalCanotBeAdedToTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalAmount does not equal to amounth calculation.
        /// </summary>
        public static string TotalAmountWrong {
            get {
                return ResourceManager.GetString("TotalAmountWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargeback cannot be created for given transaction.
        /// </summary>
        public static string TransactionCannotBeChargedBack {
            get {
                return ResourceManager.GetString("TransactionCannotBeChargedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction committed.
        /// </summary>
        public static string TransactionCommitted {
            get {
                return ResourceManager.GetString("TransactionCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction created.
        /// </summary>
        public static string TransactionCreated {
            get {
                return ResourceManager.GetString("TransactionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction does not exist.
        /// </summary>
        public static string TransactionDoesNotExist {
            get {
                return ResourceManager.GetString("TransactionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction(s) Holded.
        /// </summary>
        public static string TransactionHolded {
            get {
                return ResourceManager.GetString("TransactionHolded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is tot allowed to modify.
        /// </summary>
        public static string TransactionIsNotAllowedToModify {
            get {
                return ResourceManager.GetString("TransactionIsNotAllowedToModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Rejected.
        /// </summary>
        public static string TransactionRejected {
            get {
                return ResourceManager.GetString("TransactionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction(s) Unholded.
        /// </summary>
        public static string TransactionUnHolded {
            get {
                return ResourceManager.GetString("TransactionUnHolded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creted and Identity detailds updated.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields missing or provided invalid values.
        /// </summary>
        public static string ValidationErrors {
            get {
                return ResourceManager.GetString("ValidationErrors", resourceCulture);
            }
        }
    }
}
