# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


pool:
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: FrontendRepo
    type: bitbucket
    endpoint: "Bitbucket - vladmrvolkov2"
    name: benamardan/ecng-frontend
    ref: $(Build.SourceBranchName)


variables:
  solution: '**/EasyCard.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildNumber: $[ variables['Build.BuildNumber'] ]
  versionNumber: '1.0.0.$(buildNumber)'
  uiPath: '$(system.defaultworkingdirectory)/ecng-frontend/EasyCard/UI'


steps:
- checkout: self
- checkout: FrontendRepo

- script: dir $(Build.SourcesDirectory)
- script: dir $(system.defaultworkingdirectory)

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: replacetokens@3
  inputs:
    rootDirectory: '$(uiPath)'
    targetFiles: '**/.env.$(Build.SourceBranchName)'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTransforms: false
    enableTelemetry: false

- script: npm install
  displayName: 'npm install'
  workingDirectory: '$(uiPath)\merchant'
  
- script: npm run build $(Build.SourceBranchName)
  displayName: 'npm build'
  workingDirectory: '$(uiPath)\merchant'

- script: npm install
  displayName: 'npm install'
  workingDirectory: '$(uiPath)\admin'

- script: npm run build $(Build.SourceBranchName)
  displayName: 'npm build'
  workingDirectory: '$(uiPath)\admin'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(uiPath)/merchant/dist'
    Contents: '**'
    TargetFolder: '$(system.defaultworkingdirectory)/easycardng/EasyCard/MerchantProfileApi/wwwroot'
    overWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(uiPath)/admin/dist'
    Contents: '**'
    TargetFolder: '$(system.defaultworkingdirectory)/easycardng/EasyCard/Merchants.Api/wwwroot'
    overWrite: true

- task: replacetokens@3
  inputs:
    rootDirectory: '$(system.defaultworkingdirectory)/easycardng/EasyCard'
    targetFiles: '**/appsettings.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTransforms: false
    enableTelemetry: false

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '
    /p:DeployOnBuild=true
    /p:WebPublishMethod=Package
    /p:PackageAsSingleFile=false
    /p:SkipInvalidConfigurations=true
    /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'



- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: |
      Transactions.Api.zip
      MerchantProfileApi.zip
      Merchants.Api.zip
      IdentityServer.zip
      CheckoutPortal.zip
      Reporting.Api.zip
    TargetFolder: '$(Build.ArtifactStagingDirectory)/publishable'
    



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publishable'
    ArtifactName: 'publishable'
    publishLocation: 'Container'




