//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantProfileApi.Models.Terminal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalTransmissionScheduleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalTransmissionScheduleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MerchantProfileApi.Models.Terminal.TerminalTransmissionScheduleResource", typeof(TerminalTransmissionScheduleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00am - 03:00am.
        /// </summary>
        public static string From12amTo3am {
            get {
                return ResourceManager.GetString("From12amTo3am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00pm - 03:00pm.
        /// </summary>
        public static string From12pmTo3pm {
            get {
                return ResourceManager.GetString("From12pmTo3pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03:00am - 06:00am.
        /// </summary>
        public static string From3amTo6am {
            get {
                return ResourceManager.GetString("From3amTo6am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03:00pm - 06:00pm.
        /// </summary>
        public static string From3pmTo6pm {
            get {
                return ResourceManager.GetString("From3pmTo6pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06:00am - 09:00am.
        /// </summary>
        public static string From6amTo9am {
            get {
                return ResourceManager.GetString("From6amTo9am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06:00pm - 09:00pm.
        /// </summary>
        public static string From6pmTo9pm {
            get {
                return ResourceManager.GetString("From6pmTo9pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09:00am - 12:00pm.
        /// </summary>
        public static string From9amTo12pm {
            get {
                return ResourceManager.GetString("From9amTo12pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09:00pm - 12:00am.
        /// </summary>
        public static string From9pmTo12am {
            get {
                return ResourceManager.GetString("From9pmTo12am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
    }
}
