//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantProfileApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MerchantProfileApi.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Feature must be enabled first.
        /// </summary>
        public static string ApiFeatureMustBeEnabled {
            get {
                return ResourceManager.GetString("ApiFeatureMustBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Created.
        /// </summary>
        public static string ConsumerCreated {
            get {
                return ResourceManager.GetString("ConsumerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Deleted.
        /// </summary>
        public static string ConsumerDeleted {
            get {
                return ResourceManager.GetString("ConsumerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {count} Consumers Deleted.
        /// </summary>
        public static string ConsumersDeletedCnt {
            get {
                return ResourceManager.GetString("ConsumersDeletedCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Updated.
        /// </summary>
        public static string ConsumerUpdated {
            get {
                return ResourceManager.GetString("ConsumerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File required.
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved.
        /// </summary>
        public static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Created.
        /// </summary>
        public static string ItemCreated {
            get {
                return ResourceManager.GetString("ItemCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Deleted.
        /// </summary>
        public static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {count} Items Deleted.
        /// </summary>
        public static string ItemsDeletedCnt {
            get {
                return ResourceManager.GetString("ItemsDeletedCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Updated.
        /// </summary>
        public static string ItemUpdated {
            get {
                return ResourceManager.GetString("ItemUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max file size is 1MB.
        /// </summary>
        public static string MaxFileSizeIs1MB {
            get {
                return ResourceManager.GetString("MaxFileSizeIs1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only CSS files are allowed.
        /// </summary>
        public static string OnlyCSSFilesAreAllowed {
            get {
                return ResourceManager.GetString("OnlyCSSFilesAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images are allowed.
        /// </summary>
        public static string OnlyImagesAreAllowed {
            get {
                return ResourceManager.GetString("OnlyImagesAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key Updated.
        /// </summary>
        public static string PrivateKeyUpdated {
            get {
                return ResourceManager.GetString("PrivateKeyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Key Updated.
        /// </summary>
        public static string SharedKeyUpdated {
            get {
                return ResourceManager.GetString("SharedKeyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal is disabled.
        /// </summary>
        public static string TerminalIsDisabled {
            get {
                return ResourceManager.GetString("TerminalIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Updated.
        /// </summary>
        public static string TerminalUpdated {
            get {
                return ResourceManager.GetString("TerminalUpdated", resourceCulture);
            }
        }
    }
}
