//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchants.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merchants.Shared.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External System Removed.
        /// </summary>
        public static string ExternalSystemRemoved {
            get {
                return ResourceManager.GetString("ExternalSystemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External System Saved.
        /// </summary>
        public static string ExternalSystemSaved {
            get {
                return ResourceManager.GetString("ExternalSystemSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Created.
        /// </summary>
        public static string MerchantCreated {
            get {
                return ResourceManager.GetString("MerchantCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Updated.
        /// </summary>
        public static string MerchantUpdated {
            get {
                return ResourceManager.GetString("MerchantUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Created.
        /// </summary>
        public static string TerminalCreated {
            get {
                return ResourceManager.GetString("TerminalCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Disabled.
        /// </summary>
        public static string TerminalDisabled {
            get {
                return ResourceManager.GetString("TerminalDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Enabled.
        /// </summary>
        public static string TerminalEnabled {
            get {
                return ResourceManager.GetString("TerminalEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal template approved.
        /// </summary>
        public static string TerminalTemplateApproved {
            get {
                return ResourceManager.GetString("TerminalTemplateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Template Created.
        /// </summary>
        public static string TerminalTemplateCreated {
            get {
                return ResourceManager.GetString("TerminalTemplateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal template disabled.
        /// </summary>
        public static string TerminalTemplateDisabled {
            get {
                return ResourceManager.GetString("TerminalTemplateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Updated.
        /// </summary>
        public static string TerminalUpdated {
            get {
                return ResourceManager.GetString("TerminalUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Invited.
        /// </summary>
        public static string UserInvited {
            get {
                return ResourceManager.GetString("UserInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User linked to Merchant.
        /// </summary>
        public static string UserLinkedToMerchant {
            get {
                return ResourceManager.GetString("UserLinkedToMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Operation Failed.
        /// </summary>
        public static string UserOperationFailed {
            get {
                return ResourceManager.GetString("UserOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Operation Success.
        /// </summary>
        public static string UserOperationSuccess {
            get {
                return ResourceManager.GetString("UserOperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles updated successfully.
        /// </summary>
        public static string UserRolesUpdated {
            get {
                return ResourceManager.GetString("UserRolesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User unlinked from Merchant.
        /// </summary>
        public static string UserUnlinkedFromMerchant {
            get {
                return ResourceManager.GetString("UserUnlinkedFromMerchant", resourceCulture);
            }
        }
    }
}
